language: java
before_install:
- chmod +x mvnw
- curl -L https://github.com/docker/compose/releases/download/3.3/docker-compose-`uname
  -s`-`uname -m` > ./docker-compose
- sudo mv ./docker-compose /usr/bin/docker-compose
- sudo chmod +x /usr/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t 5033/project234-backend  .
- docker push 5033/project234-backend
- docker pull dto80/project234-frontend
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: ZPBOD1Q77x7HQMIjiAmaY9oIUdUxNz7WS4n3PrYjq3jKydjWP1RIP6ISk2/QWynm95HlNfaUo1UZpq+P/NclRsoqgYeSx1HYZefWizKebDIvVTRnfd3spWPn40inGOtR+Cb2tyva1RLIz/u0xcd3CfQkr5ctvLZbVVZC2HuIu+z8VZZGw5J0tYvlu2ddzlZkp7m62OgEEx/4N63qF8wA0YQRc64hN4jHPTTKZBhlIAjFtTiAMpw9oF55tiA+oiVh8modN0I6UHI1W8VveJLgOSusvVWhJoDFOnQoOAkF7m/eCEnkbufBWVieaARFRyB1F96K7hNi4jJ3WkvKgoZR6Ju/BSt16jV+lzpt1RqQ4KGgvadivQcngHgadqvRnHo3NiBXXEGKbmuIeYjvO7mua8hQIjm1MddxEsttAh85O4zN4df69Pf6HWT+ftZdNdOxcObuWkOJtEnsu9aYNQCW9cxOrHq+Z8/poppg9lQQo6FmEsMdwYqCx/hQNoQPG6r/MVSw+Rzegki5MhEQXbqZreDHd88YP5BcbIMgy2E4cb1BsCi0snPE+CdY9rBRfRedL7jtkfMaRlUDcUBTFgCXB5Eq9wT7Z6ly0yO33gYQH4JYTvJEANEqksEMCQP3Q/IV9YlOI14nP3YMDGUX1IkUiD2fjzYJgY1T+mGvt40GO+s=
  - secure: jWtLrHUSwIm9vUZ+O8JHGNerdlqUaZNq0CddahwyZ/9ECwFiX9Tuj/yLNi8+qkzTOtITsH+8lVnriivX8k+Mxm+EZpnn0oGNyKj/Z1nwUPWHjWWDmwrCtSI7Cu1AVwAR1rkqtZRTC3zyEpOPT5CJVBEy8OJNBFq4eUw8qtkUaR4nS1E74eUHEkGP4zZxkQ0MWBrRIgwg71MnXXRZxECFdq8UzBWyC5Q3t3bapKypAXlhfnJCo5oEe+09ZcrvR5euLfVaA4Bj365CqFJBOXnuf/M48Nmkb1e2oV11tVINj8jgIZwgVn7V38IJJmZJJolhO2YEjCdnbyku9kvVHbDGPBJGk0ex7QH+r7uRNsdX/m0RhpK3/a0cYs91GbAosGXzGvLao9uAtD3SlBmq1FEg/MEt3VyNg+a9XIllZLahkPUgnRWOX8sTr4jj6DeEF24+hmXq8X8cxKBbbp1ONUoe9yluQZOf1IqzrbsIpOIPapTn+T36Qiis+1eZgRP0ItEu9teEnDH49C7iTL1VsO9PqkS8yjOGXVpOiicxwaD082FoGg7r+56fEhv3N0bnb15ftJKCVPXUa7Ic4FEke0ZckLqmHBqU0Ou89JxZIug8ctwLgxZgSUClC5qXOWL5Xc0jN0j2msZfn7W/TZkFDBWZ0eXML8KYo8HyF+7atXURIa8=
  - secure: do/dc+I0B5KF8dvSF1rBeq4GOZG85FODOe2jBNMcH1mQFipJdhY6+D8YhZgAxmNFN8lHryfzRgCggs4s/qq/kkhfHpxOKSZNP0EdPm0bZe5oZlCfx9at5zjhz4e1Dr0+b03uEAOPclNk8YwgEEpWiI5uyuJB1aaOvdBTtVku4+gxPlk7KcyErfbzeK3ZyaiWh/UNBKU2B3FoPkON6zQyizV59dZxi7Rp9FfygOtPztOIp2DluUvgDSD3qxnY0Uv3qKEJjRQN1w1HFnHfdB/6oqEUxck4n6qViSeup1iakyLdZl4q+8yoV46/TBLlfB71L99mu4QOrnSLqQCQJ/4y20AHecbsIM4/TmYjwIv0L4HigMqyB2ohSLDHE212R8sMvX2swPyF+xzLF8iuwo8pWRU3koFcDQoqad1kUpFYJDqBVtJ/6P5A4yRCX+AIKiIxh6nI5qASbYoAke39IpgYTAf9HfNG6owrUVt2tIsYd4m7vSAX7TP2zirsy7xYnF1xWqlv1jh40kxuQYaKzPuaI6kZZ6nia4Pcgil+2h5j2ECsyF529FKI/6yFL3F/tfHptfxb4AN6N1SvIhEgcIStlAdgEhxCayDfUh/hlSJAlYgP07CGE+V0aFBnTKUduaFBqNPbbXk4j6hn9oG0RvMyM24NVlVN/2H+z1Xo/KTUGMk=
