language: java
before_install:
- chmod +x mvnw
- curl -L https://github.com/docker/compose/releases/download/3.3/docker-compose-`uname
  -s`-`uname -m` > ./docker-compose
- sudo mv ./docker-compose /usr/bin/docker-compose
- sudo chmod +x /usr/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t 592115022/project234-backend  .
- docker push 592115022/project234-backend
- docker pull dto80/project234-frontend
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: ZiAF+rRI/ndEMDEDTSlV1hZyhc29UYs12YtlvgO0Syxoz1GdKQmivMUtuHNZzIR1Nog3nJcL9FanIg4hP+cddUfFoStkNLsuWy79PjkbuevorhLsbh44Ygijm03/fdM0O7n9fkv+Zmae71aI3SWgGDdt0hmnD0IrwAujWCfrCMAlw9Z3M1MWuDHgzv3stQaudp1E52lo6EGOlPPSNBi8W7GcLw3ynvScIhY0FKi+t9YASPXHK1j9bQK7kQNe1AtnIM2O9CYyDRE+XKN3qLDZwBTOYhger2XVuMTZ04UV6omJvD7goBYMKyE/prwhYamY5u1Rlxsykar9KMesS/tq4SLOoB8PZ9738MBqXJLilPjLW7TvmKxigaDTg7r7+m9tQ9WvnGDD/WT/rTftPhMO5uZsPf+9ktv9haBaCXOO9DdWh/O/klLiJYp8ofTu/3QU6XGR/ah/4Fi0AwHS+MF78ZfIpo3Qbhuo1Yv+AMAPuFlJyw7NUIGwl3cAhILq7u0fUBTXjrWtVARxfnJ4hH+LT05x4tZyngjIM/6HseDAYwZ6vtbdD/P1A9o1NymgS3/WQAdMgwFOaiKE7p4Ulxe+o6U4UNYgl7E+kugv09douJjVadx9WfpkAeynojhMo7AkMebptmngcbCTm2mCAE58I+LLY4QtKaKciEQKlMJzPI0=
  - secure: ex7ka4f+rYfwd++8LobBQdKNQ+f+GerX8/QUzOjKVo2WKbLFyv3ok8iG+6bawsvLz8dkkcmvqdpTTDTxNNhTrP3mrY/mmUBSb+B1Im3ZDEoAcTmuU1//BedGQRvVasqjwu7Scim65rIf8FY3xdW9YDI85/9YYI0qn18ByRti8ATfGJyJCg0FvJ/bSTTqcedQzb/qXCGwtnN8WeKG/aeNe8lGWbmVpy1baEvGqEWwuHJc7O9PNUoRiHXHcj+TmZ81lPDvK0qXQdUURBOUdO9Ed2fUa+BMbftkZ1mYbFhAblqzsOcsNA1f1IhGn6C9Cl/lwj/mi9HdrmuETlE/GQExZK6i030un82eHRGRHro3HX2Gu8QbWLOymWED3fs4+rLw403iPHasqy8esHLXTTAVSAjiGExpza9mKRb9KoGj5mUOBMmN/91iPknvIVnQ9QhSGS6zPCWeTxNTdQpu3NqUWP6kMNzZSmuENtmgxAJLx5X5q/4VHhQRHLvrk7jkyoQOl4x/NLsi+u5dhUv2D9ElaktfQ1k5iMMMVrl8QUcgFDE5DMI2XFbw2T+6BWNdy7Y6wWQXSjfDPHCAkFD/plG0a5BC/ZFv+cHHn3+pC/5dPGz0mjHnQfiDOwv+303hGxS3DLrO65bHpe0wvcuaZTwWQDVLM2PcJF7h3X3ElWpUHPE=
  - secure: SF497kdxxQLTz1vp3zmaq8swtgD9Y8JUPSORhAvhAtIXqz9yJMv50vDmQ4gTK/8+b5D1venqRrnder/vmkLmhSGtzS9ZpMu/z8eO/rNMlAgOhHSmdC+Rv54jpWnqFKPHmCbd1tUVc3RCF5NX4nEuEETrrUBtVy8Hp1FpBc9J/NILr2WtTUm4Fbw7bOpZL89ylF5JBE9OwkzVMMtSvIgpTToUd71eH9ZVZtkLb7aAHSOETS7e+6S3rvDshUgqyfGcQSaI9JuEHu/O6kzsjtMEVOqYwQ1nF9+bT42UKTjfkDsmGuzfM2k019FdQv+5Zy78g0RstfQ3vrXonIsrA1wYNowGYjrg/K3YralA3EXJBXjHG5y4XTWk2Z/zr1Jfnj05cKRHLMxL30bGeiCb85tk+me/gTamcrOuaiKpdfjbge4SiEERm938eILc38uAuwhWXQs6afofdSnp2KyUpZ7X2VDHB9q7269J2zBLvnu4y4OX2FWA7w57qRYdrKjrc90mlFL087+UiBQ6AlRNAcXNnDMlU/MyMQKrC3AXECZWLEJczTY910AL2nlKsCHZS+NCOgFm7b/6ZdUU7xYiG2pvH3T/MQ7wFprQL2Zt8ZYCjAenKb1Dh5x0kdjj6FUim/3MGmtLpGiqfeo2CTnAFczw0OUfNpEdHQ4P5Sd2AJvB2e4=
