language: java
before_install:
- chmod +x mvnw
- curl -L https://github.com/docker/compose/releases/download/3.3/docker-compose-`uname
  -s`-`uname -m` > ./docker-compose
- sudo mv ./docker-compose /usr/bin/docker-compose
- sudo chmod +x /usr/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t 5033/project234-backend  .
- docker push 5033/project234-backend
- docker pull dto80/project234-frontend
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: Fg497l/AclR3//9DNtjgT1KuiQdth8xFCQiA+KGX1fa9QtXJ84qaRQD9YNrJA0XQ0VHWg3uaSZjwJY+AfBTcpJ3L+klK3ylMjjQeyzseck0OJ0bm1o7ods4SbJMUxTGbi4qRmalXu3VWZLY8mtWBVfTChkTlfqL3UJ2CHn6Ngk7WxWOWAbD+PM5wiTSrIfkEY2yZoF+hwCx3C1F6ITafEgqa5vH87LeLfyCOKyx/XzFPvYt4GBKUtmX0K5sLfelpbFWRDm/4LxsggqgkVEwrF7Bijajtj1+MckTPAjmjdzEvtvJmXKrG7qFL3cbZH6uDaNwXAYL7rlxOD1Q2LSWgfXlAO0U6Krar1bjn1nNZqG80Z1orxt0GjcQL3Dysi5T2S7ymZ2A3jEqcf5VSJx5g3sKnDviAzMRgc1Ho2OuoDRk/Z9aRsDnBwKla/Ow9RqZQN1sYp2mxzLWnU/SJiYvvTzp2uKICvKMD7B7WAEvyl5xP+gyU0O6ioIuDMr8pbghMaCcDm0GowLTjXmEwZwbRVhqm3nbrU3P5bJmcMpVJNWwWBYxWV1EyNRIRBCTJETlyXEWUbo15r7+/RBe7IT5Rw1htJ3/MjqFwwXGfUL6pv1nb3o1+hqMjtUubEQV/JYlXxprUG/HLtZmi1PMIlnHBJPLenhlq7ONxcVCGqH5Amog=
  - secure: AXz/rGllEU7n5ITsSJtbCWrcQnKy9E5C34OIvbbEqdAnza7WcK0FQZp656Jy0k3cpgrq/uewaw3/CxZAugIRxqgqBAfJB7z3teu6ixkwJk3DL7NcQQdNsZFPLhutJtclAXasbMiFXQPfihxRlWdBbKuBsYy2ziPBekSCbukdQTy8ul+rG6qITkB0LVnkO7Ih6jBD+ShbDEaOCeBtJJxtmqqB17IuKnxes9Q5OB5ZVoRr0cfGWqEmeGWrn2GQvXJsNsjItDqjE0DNLboFpQok958FJ79vhJYW9vaETko0qFcqZsSgTcSMy/She+gZajQtbra+FrfJD8j2CPxnCrdgm8G2T6He691srnvcmT9E1Cqg+19WUDhP0/PZcb41bGC2tMUipyaciqg/FiRhBZCfrxxOspc4ZuiYz2jFZm4FcIwuqy9NgObhrLnHF/Qj9dKPfFV3kxYmpZXrOI0wseDekQ299WcELBsc1I1RXbxt/2SIABr/SCqWxBvK+w5ITFfPI3yR2DYA+ZdnOP6HMl+vZNV7VExUa4jybP+tc9BiD/5kOurfLybdxRA2F4iZH7mzHgIuSkh58Rl4exwEDntTcruVMWrJRKaj3NDF67nwhXAX48FxqZF8Kg0aHJkDOOm74VVn12rFlso0yyhiW5Jy97ZvvtJLYzBFP5pNpHkpv+8=
  - secure: QM18oshjF+3c5f79jh3OJHyMd4+l1O9WgU7Uu6O1HR8huqRr95w9ONEK0aXEHuoyFRwQQtXYRBbJr3xrFkS2pQruyrIl5VWjL2Jdq9OZHxe6zK4kFveF1jMkdOpRI/NOq/LYPe84RVjmJTWObzE+/INLcVuWq+W9bLbo1XlffPH0yL0CLzoITQE9zSJzUX1nM0c/pr6nlDrR3pTHoJBgLUb0tOBRz+Xo9kKZAs7dIuCkY3S7EE9iAtB+KXjISjORCvWL7PHs8ZmeLJmBepVOAkpDYi+PII1Q0B/qC/YuI/fyIK6keOCIEG5s3JEOIxtsS2H6WvI8HjUAhQLOi9G+Ncpfs/L/xSNXhaVUG7MRCoKvswQ1jHaDUByer7x/GLdz8quThP9PJI4s7qOd+BHfqe3EDgOsGX2KMklCWTuFBMfMWT0yvZI8wEglMt/bXJZtlulCoeOMi+EXg4oIGWrh2YocHgU/90aS7OHWueUPdmluu33q+hkLT+BUWrCcFbibOr4Z5222GtDhzFRq981UtZiNBclwZd/iWdqhMIXn1Fw4X8+vuK7J5I4fRFqZFBrioUUdHG948VLgcFiHJOyKu1RPje55R3jJlum+uGUgt+OGArhuG863Irj9MLDOhAFcRzh8ScuX5rbLLz3B38kVbchHr/vCGDUKe9/QMQriSeE=
