version: '3.3'
services:
  backend:
    image: 5033/project234-backend:latest
    ports:
      - "8076:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
     - "8077:80"
    volumes:
      - type: bind
        source: /usr/set.json
        target: /usr/share/nginx/html/assets