version: '3.3'
services:
  backend:
    image: 592115022/project234-backend:latest
    ports:
      - "8011:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
     - "8012:80"
    volumes:
      - type: bind
        source: ./project/setting
        target: /usr/share/nginx/html/assets